name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deployment:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v1
      - name: 'Deploy'
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade -n shorten-url uid-generator ./deploy/helm/ -f ./deploy/values.yaml
          kubeconfig: '${{ secrets.KUBE_CONFIG }}'
