name: Integration

on: push

jobs:
  integration:
    runs-on: ubuntu-18.04
    container: python:3.8.11-slim
  
    steps:
      - name: Install container dependencies
        run: |
          apt update
          apt install -y make software-properties-common gnupg2
          add-apt-repository -y ppa:git-core/ppa
          apt install -y git
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          make init
          pip3 install -U pip setuptools
          pip3 install poetry
      - name: Run ci bundle command
        run: |
          make ci-bundle