name: Release

on:
  push:
    branches:
    - master

jobs:
  delivery:
    runs-on: ubuntu-20.04

    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Login to Github Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: docker.pkg.github.com/arashi87/shorten-url/uid-generator
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Latest Build

  deploy:
    needs: delivery
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v1
      - name: 'Deploy'
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade -n shorten-url uid-generator ./deploy/helm/ -f ./deploy/values.yaml
          kubeconfig: '${{ secrets.KUBE_CONFIG }}'
